---
- name: Login to registries
  ansible.builtin.include_tasks: registries.yml
  when: registries | length > 0

- name: Configure networks
  ansible.builtin.include_tasks: networks.yml
  when: networks | length > 0

- name: Configure containers
  ansible.builtin.include_tasks: containers.yml
  when: containers | length > 0
